name: ladylauraluck
favicon: null
layout_spectrum: 0.7981325366999954
typography_spectrum: 0.25736357481218874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3254717418458313
  lightness: 0.29437945527024567
  saturation: 0.6267751455307007
  rhythmicContrast: 0.7444386046845466
purpose: []
